#include "mfrc522.h"

/* SPI handle generated by CubeMX */
extern SPI_HandleTypeDef hspi2;

/* Change these to match your hardware */
#define MFRC522_CS_PORT      GPIOB
#define MFRC522_CS_PIN       GPIO_PIN_4

#define MFRC522_RST_PORT     GPIOI
#define MFRC522_RST_PIN      GPIO_PIN_8

static void MFRC522_Select(void)
{
    HAL_GPIO_WritePin(
        MFRC522_CS_PORT,
        MFRC522_CS_PIN,
        GPIO_PIN_RESET);
}

static void MFRC522_Deselect(void)
{
    HAL_GPIO_WritePin(
        MFRC522_CS_PORT,
        MFRC522_CS_PIN,
        GPIO_PIN_SET);
}

void MFRC522_WriteRegister(uint8_t reg, uint8_t value)
{
    uint8_t tx[2];

    tx[0] = (reg << 1) & 0x7E;
    tx[1] = value;

    MFRC522_Select();

    HAL_SPI_Transmit(
        &hspi2,
        tx,
        sizeof(tx),
        HAL_MAX_DELAY);

    MFRC522_Deselect();
}

uint8_t MFRC522_ReadRegister(uint8_t reg)
{
    uint8_t addr;
    uint8_t value;

    addr = ((reg << 1) & 0x7E) | 0x80;
    value = 0;

    MFRC522_Select();

    HAL_SPI_Transmit(
        &hspi2,
        &addr,
        1,
        HAL_MAX_DELAY);

    HAL_SPI_Receive(
        &hspi2,
        &value,
        1,
        HAL_MAX_DELAY);

    MFRC522_Deselect();

    return value;
}

void MFRC522_Reset(void)
{
    HAL_GPIO_WritePin(
        MFRC522_RST_PORT,
        MFRC522_RST_PIN,
        GPIO_PIN_RESET);

    HAL_Delay(10);

    HAL_GPIO_WritePin(
        MFRC522_RST_PORT,
        MFRC522_RST_PIN,
        GPIO_PIN_SET);

    HAL_Delay(50);
}

void MFRC522_Init(void)
{
    MFRC522_Reset();

    MFRC522_WriteRegister(
        MFRC522_COMMAND_REG,
        MFRC522_CMD_SOFTRESET);

    HAL_Delay(50);
}

uint8_t MFRC522_GetVersion(void)
{
    return MFRC522_ReadRegister(
        MFRC522_VERSION_REG);
}